/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tqxktbyw_study_packer_ListFile */

#ifndef _Included_com_tqxktbyw_study_packer_ListFile
#define _Included_com_tqxktbyw_study_packer_ListFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tqxktbyw_study_packer_ListFile
 * Method:    depack
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tqxktbyw_study_packer_ListFile_depack
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
