/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tqxktbyw_videoplayer_AesVideoDec */

#ifndef _Included_com_tqxktbyw_videoplayer_AesVideoDec
#define _Included_com_tqxktbyw_videoplayer_AesVideoDec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tqxktbyw_videoplayer_AesVideoDec
 * Method:    getkey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tqxktbyw_videoplayer_AesVideoDec_getkey
  (JNIEnv *, jobject);

/*
 * Class:     com_tqxktbyw_videoplayer_AesVideoDec
 * Method:    getIv
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tqxktbyw_videoplayer_AesVideoDec_getIv
  (JNIEnv *, jobject);

/*
 * Class:     com_tqxktbyw_videoplayer_AesVideoDec
 * Method:    depack
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tqxktbyw_videoplayer_AesVideoDec_depack
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_tqxktbyw_videoplayer_AesVideoDec
 * Method:    getData
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tqxktbyw_videoplayer_AesVideoDec_getData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tqxktbyw_videoplayer_AesVideoDec
 * Method:    setData
 * Signature: (Ljava/lang/String;Ljava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_com_tqxktbyw_videoplayer_AesVideoDec_setData
  (JNIEnv *, jobject, jstring, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
